# distillration 모델 테스트용 프롬프트
prompt_user_with_ocr = """
OCR this image to HTML table. Extract only the table region and output table structure.
Bboxes are normalized to a 0-{bbox_scale} coordinate space.

In addition to the image, you are also provided with OCR text information extracted from the same page.
Each OCR item includes recognized text and its bounding box in the same normalized 0-{bbox_scale} coordinate space.

<ocr_info>
{ocr_info}
</ocr_info>

You MUST use BOTH:
- the visual information from the image
- the provided OCR text and bounding boxes

to accurately reconstruct the table content and structure.

The OCR text should be used as the primary source of textual content.
The image should be used to resolve table structure, merged cells, reading order, and ambiguous cases.

Only use these tags ['table', 'tr', 'td', 'th', 'thead', 'tbody', 'caption', 'p', 'span', 'br', 'b', 'i', 'u', 'sup', 'sub'] and these attributes ['colspan', 'rowspan', 'style', 'align'].

Guidelines:
* Tables: Use colspan and rowspan attributes to match table structure.
* Formatting: Maintain consistent formatting with the image, including spacing, subscripts/superscripts, and special characters.
* Text: join lines properly into cell content.
* Use the simplest possible HTML structure that accurately represents the table.
* Output only table HTML.
""".strip()

# distillration 모델 테스트용 프롬프트
prompt_user__ocr = """
OCR this image to HTML table. Extract only the table region and output table structure.
Bboxes are normalized to a 0-{bbox_scale} coordinate space.

Only use these tags ['table', 'tr', 'td', 'th', 'thead', 'tbody', 'caption', 'p', 'span', 'br', 'b', 'i', 'u', 'sup', 'sub'] and these attributes ['colspan', 'rowspan', 'style', 'align'].

Guidelines:
* Tables: Use colspan and rowspan attributes to match table structure.
* Formatting: Maintain consistent formatting with the image, including spacing, subscripts/superscripts, and special characters.
* Text: join lines properly into cell content.
* Use the simplest possible HTML structure that accurately represents the table.
* Output only table HTML.
""".strip()




# prompt_user_with_ocr = """Please output the layout information from the PDF image, including each layout element's bbox, its category, and the corresponding text content within the bbox.

# 1. Bbox format: [x1, y1, x2, y2]

# 2. Layout Categories: The possible categories are ['Caption', 'Footnote', 'Formula', 'List-item', 'Page-footer', 'Page-header', 'Picture', 'Section-header', 'Table', 'Text', 'Title'].

# 3. Text Extraction & Formatting Rules:
#     - Picture: For the 'Picture' category, the text field should be omitted.
#     - Formula: Format its text as LaTeX.
#     - Table: Format its text as HTML. Use colspan and rowspan attributes to match table structure.
#     - All Others (Text, Title, etc.): Format their text as Markdown.

# 4. Constraints:
#     - The output text must be the original text from the image, with no translation.
#     - All layout elements must be sorted according to human reading order.

# 5. Final Output: The entire output must be a single JSON object.
# """.strip()
# prompt_user_with_ocr = """Recognize the text in the image and output in Markdown format.
# Preserve the original layout (headings/paragraphs/tables/formulas).
# Do not fabricate content that does not exist in the image.

# In addition to the image, you are also provided with OCR text information extracted from the same page. Each OCR item includes the recognized text and its bounding box. The OCR bounding boxes are in the same normalized 0-{bbox_scale} coordinate space.

# <ocr_info>
# {ocr_info}
# </ocr_info>
# """.strip()

# prompt_user_with_ocr = """Recognize the text in the image and output in Markdown format.
# Preserve the original layout (headings/paragraphs/tables/formulas).
# Do not fabricate content that does not exist in the image.
# """.strip()

# prompt_user_with_ocr = """Table Recognition:
# """.strip()

prompt_correction = """You are given an HTML document generated by a VLM from a document image, and a list of OCR-extracted texts from the same page.

The VLM may have made errors in text recognition. The OCR text is generally more accurate for character-level recognition.

Your task:
1. Compare the text content in the HTML with the OCR texts
2. Correct any text errors in the HTML using the OCR texts as reference
3. Keep the HTML structure (tags, attributes, layout) exactly the same - do NOT add, remove, or restructure any HTML tags
4. Only modify text content where the OCR provides a more accurate version
5. For mathematical formulas/equations (LaTeX, KaTeX), keep the original VLM text - OCR is unreliable for math
6. Return ONLY the corrected HTML, no explanations

<original_html>
{original_html}
</original_html>

<ocr_texts>
{ocr_texts}
</ocr_texts>
""".strip()

# prompt_user_with_ocr = """
# Please extract layout information from the given PDF image.
# For each layout element, output its bounding box (bbox), category, and text content if applicable.

# 1. Bounding Box Format
# - Use [x1, y1, x2, y2] in image pixel coordinates.
# - Bbox must tightly enclose the entire visual element.

# 2. Layout Categories
# - One of the following:
# ['Caption', 'Footnote', 'Formula', 'List-item', 'Page-footer', 'Page-header',
#  'Picture', 'Section-header', 'Table', 'Text', 'Title'].

# 3. Text Extraction & Formatting Rules
# - Picture: omit the text field.
# - Formula: output LaTeX only.
# - Table: output valid HTML only.
# - All others: output Markdown.

# 4. Table-Specific Structural Rules (CRITICAL)
# When the category is "Table", strictly follow these rules:

# 4.1 Table Reconstruction Priority
# - Reconstruct the table structure FIRST, before filling text.
# - Infer rows and columns based on:
#   - cell alignment
#   - ruling lines (if present)
#   - whitespace gaps
#   - consistent x/y boundaries of text blocks

# 4.2 Cell Spanning (rowspan / colspan)
# - Use rowspan ONLY when a cell visually spans multiple rows
#   (same x-range, taller height than neighboring cells).
# - Use colspan ONLY when a cell visually spans multiple columns
#   (same y-range, wider width than neighboring cells).
# - Do NOT guess spans based on text semantics alone.
# - Every rowspan / colspan must be justified by visual geometry.

# 4.3 HTML Constraints
# - Use <table>, <thead>, <tbody>, <tr>, <th>, <td> only.
# - Explicitly specify rowspan and colspan when applicable.
# - Do NOT merge cells unless visually merged in the image.
# - Preserve empty cells using <td></td> if a grid position exists.

# 4.4 Header Detection
# - Use <th> only if the cell is visually styled or positioned as a header
#   (top row, leftmost column, bold text, or separated by ruling lines).
# - Otherwise, use <td>.

# 4.5 Reading Order Inside Tables
# - Process rows from top to bottom, cells from left to right.
# - Text inside each cell must preserve original reading order.

# 5. Global Constraints
# - Do NOT translate or normalize text.
# - Preserve original symbols, spacing, punctuation, and line breaks.
# - All layout elements must be sorted in natural human reading order.

# 6. Output Validation (IMPORTANT)
# Before finalizing the output:
# - Verify that the number of columns is consistent across rows
#   after applying rowspan/colspan.
# - Ensure the HTML table can be rendered without structural errors.
# - If table structure is ambiguous, prefer:
#   more cells + fewer spans (NOT the opposite).

# 7. Final Output
# - Return a single JSON object.
# - Each layout element must include:
#   - category
#   - bbox
#   - text (if applicable)
# """.strip()

# prompt_user_with_ocr = """
# OCR this image to HTML, arranged as layout blocks. Each layout block should be a div with the data-bbox attribute representing the bounding box of the block in [x0, y0, x1, y1] format. Bboxes are normalized to a 0-{bbox_scale} coordinate space. The data-label attribute is the label for the block.

# In addition to the image, you are also provided with OCR text information extracted from the same page. Each OCR item includes the recognized text and its bounding box. The OCR bounding boxes are in the same normalized 0-{bbox_scale} coordinate space.

# <ocr_info>
# {ocr_info}
# </ocr_info>

# You MUST use BOTH:
# - the visual information from the image
# - the provided OCR text and bounding boxes

# to accurately reconstruct the document content and layout.

# The OCR text should be used as the primary source of textual content.
# HOWEVER, for mathematical expressions and equations, the visual information from the image MUST be prioritized over the OCR text. OCR text for equations may be incomplete or incorrect and should only be used as a secondary reference.

# The image should be used to resolve layout, structure, grouping, reading order, and ambiguous cases.

# Each layout block should:
# - group together relevant OCR text items based on spatial proximity and visual layout
# - have a data-bbox that tightly encloses all OCR items belonging to that block
# - preserve the correct reading order

# Use the following labels:
# - Caption
# - Footnote
# - Equation-Block
# - List-Group
# - Page-Header
# - Page-Footer
# - Image
# - Section-Header
# - Table
# - Text
# - Complex-Block
# - Code-Block
# - Form
# - Table-Of-Contents
# - Figure

# Only use these tags ['math', 'br', 'i', 'b', 'u', 'del', 'sup', 'sub', 'table', 'tr', 'td', 'p', 'th', 'div', 'pre', 'h1', 'h2', 'h3', 'h4', 'h5', 'ul', 'ol', 'li', 'input', 'a', 'span', 'img', 'hr', 'tbody', 'small', 'caption', 'strong', 'thead', 'big', 'code'], and these attributes ['class', 'colspan', 'rowspan', 'display', 'checked', 'type', 'border', 'value', 'style', 'href', 'alt', 'align'].

# Guidelines:
# * Inline math: Surround math with <math>...</math> tags. Math expressions should be rendered in KaTeX-compatible LaTeX. Use display mode for block math.
# * Tables: Use colspan and rowspan attributes to match table structure.
# * Formatting: Maintain consistent formatting with the image, including spacing, indentation, subscripts/superscripts, and special characters.
# * Images: Include a description of any images in the alt attribute of an <img> tag. Do not fill out the src property.
# * Forms: Mark checkboxes and radio buttons properly.
# * Text: join lines together properly into paragraphs using <p>...</p> tags. Use <br> tags for line breaks within paragraphs, but only when absolutely necessary to maintain meaning.
# * Use the simplest possible HTML structure that accurately represents the content of the block.
# * Make sure the text is accurate and easy for a human to read and interpret. Reading order should be correct and natural.
# """.strip()
